"""Add subjects and many-to-many relationship

Revision ID: 454ee7bc7082
Revises: 628fab242685
Create Date: 2025-06-30 01:34:43.401380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454ee7bc7082'
down_revision = '628fab242685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student_subjects',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'subject_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
