"""Fix classroom_id foreign key in User model

Revision ID: b06cf5b8ac7b
Revises: 4054c41efb70
Create Date: 2025-06-27 09:45:24.318783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06cf5b8ac7b'
down_revision = '4054c41efb70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_users_classroom_id',  
            'classrooms',
            ['classroom_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_classroom_id', type_='foreignkey')  # ✅ Drop by name
        batch_op.drop_column('classroom_id')
    # ### end Alembic commands ###
