"""empty message

Revision ID: cae65f199441
Revises: eaeb0470fb26
Create Date: 2025-06-26 15:17:47.758641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae65f199441'
down_revision = 'eaeb0470fb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('classroom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('guardian_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('guardian_contact',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('guardian_contact',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('guardian_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('classroom_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
